apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: l9qii8xtl-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:0c2f671ff9bc64c5f6a4f6ea6260deec75bd50d1@sha256:8bc1beba1ecba561af4a6d87178266cefcd14e4c4cb8dcb83378056bb6d6900c
          name: container-image
